# Generated by Django 3.2.9 on 2021-11-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AlterModelTable(
            name='offer',
            table=None,
        ),
    ]
